//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsForms2
{
    using System;
    using System.Collections.Generic;
    
    public partial class attribute_value
    {
        public long id { get; set; }
        public long product_id { get; set; }
        public long attribute_id { get; set; }
        public string value { get; set; }
    
        public virtual attribute attribute { get; set; }
        public virtual product product { get; set; }
    }
}
