//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsForms2
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_item
    {
        public long id { get; set; }
        public long order_id { get; set; }
        public long product_id { get; set; }
        public long product_size_id { get; set; }
        public long quantity { get; set; }
        public long price { get; set; }
        public long discount_price { get; set; }
        public long total_price { get; set; }
    
        public virtual order order { get; set; }
        public virtual product product { get; set; }
        public virtual product_size product_size { get; set; }
    }
}
