//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsForms2
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_notification
    {
        public long id { get; set; }
        public long notification_id { get; set; }
        public long user_id { get; set; }
        public string status { get; set; }
    
        public virtual notification notification { get; set; }
        public virtual user user { get; set; }
    }
}
