//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsForms2
{
    using System;
    using System.Collections.Generic;
    
    public partial class voucher
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public voucher()
        {
            this.orders = new HashSet<order>();
        }
    
        public long id { get; set; }
        public string code { get; set; }
        public string name { get; set; }
        public string type { get; set; }
        public long discount_rate { get; set; }
        public long minimum_to_apply { get; set; }
        public long apply_limit { get; set; }
        public long quantity { get; set; }
        public System.DateTime valid_from { get; set; }
        public System.DateTime valid_to { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order> orders { get; set; }
    }
}
