//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsForms2.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class jewelryStoreManagementEntities : DbContext
    {
        public jewelryStoreManagementEntities()
            : base("name=jewelryStoreManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<attribute> attributes { get; set; }
        public virtual DbSet<attribute_value> attribute_value { get; set; }
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<collection> collections { get; set; }
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<notification> notifications { get; set; }
        public virtual DbSet<order_item> order_item { get; set; }
        public virtual DbSet<order> orders { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<product_size> product_size { get; set; }
        public virtual DbSet<user_notification> user_notification { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<voucher> vouchers { get; set; }
    }
}
