//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsForms2.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public order()
        {
            this.order_item = new HashSet<order_item>();
            this.vouchers = new HashSet<voucher>();
        }
    
        public long id { get; set; }
        public long customer_id { get; set; }
        public System.DateTime order_date { get; set; }
        public string status { get; set; }
        public string shipping_method { get; set; }
        public long shipping_fee { get; set; }
        public long total_product_price { get; set; }
        public long promotion_discount { get; set; }
        public long free_ship_discount { get; set; }
        public long total_price { get; set; }
        public string note { get; set; }
        public long user_id { get; set; }
    
        public virtual customer customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_item> order_item { get; set; }
        public virtual user user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<voucher> vouchers { get; set; }
    }
}
