//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsForms2.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class product_size
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product_size()
        {
            this.order_item = new HashSet<order_item>();
        }
    
        public long id { get; set; }
        public long product_id { get; set; }
        public string size { get; set; }
        public long price { get; set; }
        public long discount_price { get; set; }
        public long discount_rate { get; set; }
        public long stock { get; set; }
        public long sold { get; set; }
        public bool is_deleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_item> order_item { get; set; }
        public virtual product product { get; set; }
    }
}
